### ISSUE TITLE
Generic on.update functionality

### ISSUE THREAD

**Issue by mehdi-cit** [arqex/freezer#10]
Hello and thank you for what seems like a very nice and lean library :+1: 

I wonder whether it'd be possible and even desirable to have a more generic -more generic in my mind- on.update functionality as described below:
```
// Browserify/Node style of loading
var Freezer = require('freezer');

// Let's create a freezer store
var store = new Freezer({
    a: {x: 1, y: 2, z: [0, 1, 2] },
    b: 'Hola'
});
// Listen to changes in the store
store.on('update', function(changeList){
    console.log( 'I may only be triggered after data.endTransaction() is invoked' );
    //changeList = [
     // {path:'a.z', newData:['a', 0, 1, 2, 3, 'z'], oldData:[0,1,2]} ,
     //{path:'b', newData:'Hello', oldData:'Hola'} 
   //];
});

var data = store.get();
data.begingTransaction();
data.a.z.push(3).unshift( 'a' );
data.b = 'Hello';
data.a.z.push('z');
data.endTransaction();
```

Thanks again.

**Comment by arqex** [comment]
HI @mehdi-cit 

That is related to the not-implemented-feature transactions

https://github.com/arqex/freezer/issues/2

Currently, `update` event is only triggered once per tick so, even without the transaction, your code would trigger just one event in the store.

I don't think that creating a changeList of the paramenter of the event listener is a good idea, instead of that the listener receive the whole new store data.

The purpose of the library is to forget of what properties have changed and only listen to any change for re-rendering completely.It is easier to manage the apps that work that way than cherry picking the changes to update only the affected parts, that's why the event listeners receive the new data.

**Comment by mehdi-cit** [comment]
Thanks for the prompt reply arqex!

Are you suggesting that React's diffing would ensure that the process is efficient (fast rendering)? 
I actually was contemplating the usage of freezer in a different setup (no React). But I guess freezer is really meant to be used with React and equivalent!

**Comment by arqex** [comment]
Yes, freezer is thought to be used refreshing the whole UI on every change, it makes react (or equivalent) faster because you can check when a subtree should be updated just with a simple comparison

```js
var doUpdate = ( newData.foo != oldData.foo );
```
Since data properties are immutable, if `newData.foo == oldData.foo` you feel sure that the node doesn't need to be updated, no matter how deep is the data that `newData.foo` contains.

If you want to control exactly what to update in your UI based on the changes in your store, maybe you should have a look at 

https://github.com/mquan/cortex

or

https://github.com/Yomguithereal/baobab

**Comment by mehdi-cit** [comment]
Thanks for confirming my assumptions.
Indeed cortex author has just (18 days ago) implemented the sought after feature:
https://github.com/mquan/cortex/issues/52
I don't know how I missed that.
