### ISSUE TITLE
Nested Freezers

### ISSUE THREAD

**Issue by kuraga** [arqex/freezer#12]
Good day!

Can I store `Freezer` object in a `Freezer` object?

**Comment by arqex** [comment]
Hi @kuraga 

You mean to have more than one copy of a node? Like...

```js
var store = new Freezer({ a: [1,2,3]}),
  data = store.get()
;

data.set({b: data.a});
```

This is possible and really useful, everytime you update a, b will be updated since they are the same object. If they have different parents the parents of both will be updated.

If you mean a complete Freezer object, it is possible, but not really useful, because changes in the inner freezer won't trigger an update event in the outer one.

If you want to listen to changes in a specific node you can use the `getListener` method:

```js
// Continuing the previous example
var listener = data.a.getListener();

listener.on('update', function(){
  console.log('hey!')
}

data.a.push(4); // logs hey!
```

**Comment by kuraga** [comment]
Thanks!
