### ISSUE TITLE
Freezer combined with other libs such as Underscore, Lodash or Lazyjs.

### ISSUE THREAD

**Issue by ArnoBuschmann** [arqex/freezer#13]
While referring to this article "Switching from immutable.js to seamless-immutable":

http://noredinktech.tumblr.com/post/107617838018/switching-from-immutable-js-to-seamless-immutable

I indeed wondered about two things:

- Could Freezer adapt the argument of "backwards-compatibility with normal Arrays"?
- Does it make sense to combine Freezer with libraries such as Underscore, Lodash or Lazyjs?

While backwards compability could be some sort of selling point for freezer, the combined use with other libs such as Underscore leads to concrete implementation questions on what is possible, what not or what would be the best way to do it?

**Comment by arqex** [comment]
Hi Arno!

You are always sharp with your comments! I think that common array compatibility and the use along underscore alike libraries can be a nice way of promoting freezer.

Unfortunately I can't imagine on a good example for using both libraries together. There is another issue open that ask for simple examples of use of freezer, and again all the demos that come to my mind are complex, and the reason is that freezer shines on complex examples with a lot of nested data.

I have been working a lot lately and I don't have so much time to think on examples, so any idea is welcome. Freezer.js is a really helpful library and it should be known by more developers.

**Comment by ArnoBuschmann** [comment]
Hi Javi,

I guess the idea is to draw a line between a library that handles immutability and libraries such as Underscore and their alikes.

Quoting the Underscore site:
>
Underscore is a JavaScript library that provides a whole mess of useful functional programming helpers... [it] provides over 100 functions that support both your favorite workaday functional helpers: map, filter, invoke — as well as more specialized goodies

Of course we have methods such as map, filter, reduce already with normal arrays but people are using libraries such as underscore to have a wider range of methods for functional programming purposes.

Now when you have a look at Immutable.js, let's say take its iterable "map": http://facebook.github.io/immutable-js/docs/#/Map it's visible, it has 94! methods. Now we can compare these methods with the ones Underscore or Lodash are providing and see, that they are very similiar in what they try to accomplish.

Let's say, we could decouple these "libraries for functional programming" from the library that handles immutability. Wouldn't it be nice, that a Freezer user could pick a functional library of choice?

I mean, it doesn't even end just with Underscore and Lodash. Have a look at Ramda http://ramdajs.com/ which is introducing very cool concepts, that differentiate themself a lot from how Lodash/Underscore is working. (More on that in this video https://www.youtube.com/watch?v=m3svKOdZijA) Just think about how thousands of Ramda users might love to use Freezer for adding immutability ;) (Granted it makes sense, which I am still not sure yet, lol)

Final thought: If there would be something like an interface, a bridge between functional programming libraries on one side and freezer on the other end, it could be a big deal maybe? And even if it's not a programmatic solution but just a detailed blogpost on how to combine both, Freezer would benefit a lot.

But maybe my thoughts are completely nonsense in that both ends are not "bridgeable" in a useful way? And that's why immutable.js going to integrate all these methods into its own library? What do you think?

**Comment by arqex** [comment]
Hey Arno!

It is the first time I have a look at Ramda and I think it is outstanding! It is pure functional programming in a tiny library, it is simply great.

The use of this kind of libraries along with freezer doesn't require any kind of adapter and, from my point of view, the purpose of both libraries are different and complementary.

Rambda is perfect to manipulate data before output it, you can apply some functions to get the result you are looking for and use it. But Rambda is not about the data, it is about the manipulation

Freezer is perfect to store a state, it is meant to contain the source of truth that can be used by Rambda to get the results. Freezer is about the data. And you can use freezer and rambda together that way out of the box.

The good thing about functional programming is that the original data is preserved, so it is like using immutable data. Whatever data you pass as argument is never modified, new data is created with the manipulations applied. If you need to store the result of some rambda manipulation, you can use freezer again.

You always come out with nice ideas Arno, thanks, maybe I should write an article about FRP as did @christianalfoni :)

Ey Arno, I am assisting to http://jsconfbp.com/ maybe you can take some time to assist too!

Cheers,
Javi

**Comment by christianalfoni** [comment]
Bring on the FRP ;-) :+1:  Exciting stuff!

**Comment by arqex** [comment]
Yep Christian!

And difficult to grasp, as you said in your article :) 

I need to think of a simple example if I want to write something about the matter.

**Comment by ArnoBuschmann** [comment]
Hi Javi, thanks for asking, the speaker list of JSConf looks great and I'd love to especially listen to Matthew Podwysocki, André Staltz and Mikael Brevik. Unfortunately I have no time on these days, so I can't join. Will there be videos of the talks after the conference?

Great to hear that Underscore/Lodash/Ramda should work seamlessly together with Freezer! Yes, another FRP article sounds good :+1:  ;)

**Comment by ArnoBuschmann** [comment]
Interesting Twitter discussion on the definition of FRP: https://twitter.com/mattpodwysocki/status/586170112568205312

**Comment by arqex** [comment]
Yes! It is indeed a nice discussion. FRP term has a lot of hype, but you can do reactive programing perfectly without being functional.

From my point of view, the functional approach is good because it is elegant, legible, reusable and it doesn't mutate the original data, and that get you rid of a lot of problems, but it doesn't imply reactivity.

**Comment by ArnoBuschmann** [comment]
Javi, short feedback before closing this issue: I took my dev stack, dropped Immutable and replaced it with Freezer. It works great and now I don't have to use all the already implemented methods of Immutable (>100) anymore but can use Ramda instead - perfect! :+1:

**Comment by marquex** [comment]
Cool,

Thanks Arno, I am glad that you use Freezer on your projects. I am using it too and (it is bad I say this because I am the creator) it is the best store for react, but it is a bit tricky when you want to update more than one part of the store at the same time.

I have some tricks for doing so, but if you find yourself in some problems maybe you find better solutions. Would be nice to have feedback on those cases :)
