### ISSUE TITLE
Saving to server. Finding changes

### ISSUE THREAD

**Issue by enricribas** [arqex/freezer#17]
So I really love this idea. I love the idea of having one source of truth for a page with the "data store" at the top. I love passing down the part of the data to each components that cares about it. Making a change to any part of the data runs the "update" method on the listener at the top no matter how deep the components are nested, amazing!

Here is my question...
If I want to persist changes to a server, the update method gets the "new data" as its argument (all of the data), but how do I know what changed so I can persist that to the server?

It would be great if the params were (completeData, changedData). Then I could either update the item if it had an id or create a new one if id was missing. 

Am I missing something? How are other people doing this?

Hopefully this is clear, hard to explain.

**Comment by arqex** [comment]
Hi Enric,

I'm glad you liked it :)

First versions of freezer had that functionality, but later it changed to only trigger one update event on every tick, so it was difficult to buffer all the changes and what changes. Also that needs to calculate the path of the change in the tree, and working with paths is messy, so I decided to keep it simpler and remove it.

I use freezer in a Flux way so, instead of letting the views call the updating method directly, the views dispatch an action, that action perform the changes, and that is the perfect way to persist the changes in the server. 

I think that is, in some way, turning your approach upside down, it is not freezer that tells you what was updated, it is you what tell freezer what is going to change so you can sync the server.

**Comment by enricribas** [comment]
Thanks for the update. 

We currently use Reflux and it works well, it's just annoying to have have logic in the top level store, that knows about the specifics of the each lower view, so you end up with a ton of specific SomethingFetch(), SomethingUpdate, SomethingElseFetch() Actions in your store. The more nested the data the more actions you need to deal with the specifics. 

For me the beauty of an immutable store was that the data is king and it knew what changed and how to deal with it. 

Personally, I think the performance hit is worth all the extra code that is needed but not sure what the community feels about this. If I need to make actions for each thing, not sure I really see as much value in something like freezer. 

Sorry just trying to understand it all.

**Comment by aktxyz** [comment]
Can you explain the "tick" piece of the process?

reading thru the stagas nexttick github repo is not giving me an epiphany :)

https://github.com/stagas/nexttick

**Comment by arqex** [comment]
@enricribas If you have deep nested data, freezer will help you to update those deep nodes, no matter you call the update methods in your views or in a top level store, just pass the frozen node as an argument, and use it to make the update easy. 

You are right when you say that the beauty of the immutable is that the data is the king, that is exactly the point. But a store like freezer is not focused on what has changed, but just on the fact that something has changed.

When you think about a performance penalty for using freezer you are thinking about re-rendering the full component tree on every change, and you make good thinking that way. It is really easy to think about your app workflow when you know that everything will be re-rendered on a store change. That hit is not big thanks to the dom diff algorithm that React uses, and it is even none if you use the PureRenderMixin with an immutable store like Freezer.

The same way you should think about persisting your data in the server, it is better to update a full model than check what has changed to only make a partial update. If you want to make it in a reactive way, try to use the `getListener` method in the nodes representing your models in order to synchronize with the server on an update, and store the full model. Fine grained updates just doesn't worth the effort.

**Comment by arqex** [comment]
@aktxyz The tick refers to the fact that javascript machines are always in a loop to dispatch events. 

See http://blog.carbonfive.com/2013/10/27/the-javascript-event-loop-explained/

Basically in every event loop iteration, javascript engine check if some event has been triggered and call to its event handlers. When I say that freezer triggers the update on the "next tick" after a change, it means that you can make all the changes that you want to the store sequentially, and all of them will trigger just one 'update' event when all the current execution loop has finished.

Every loop iteration is called tick because in nodejs there are a `process.nextTick` to exectute code when the current iteration is over:

http://howtonode.org/understanding-process-next-tick
