### ISSUE TITLE
How did you create the custom array?

### ISSUE THREAD

**Issue by christianalfoni** [arqex/freezer#4]
Hi @arqex,

I have been looking through the source code and playing with an immutability API of my own. Mostly to understand how Freezer is created :-)

What I really do not understand is how you made the FrozenArray behave exactly like a normal array. I have been reading lots of documentation on the web and I feel that I have tried everything.

What you basically do is:

```javascript
// Without the extended/override methods
var FrozenArray = Object.create(Array.prototype);
var array = Object.create(FrozenArray);
```
But this array will not behave like a normal array. For example if I would do this:

```javascript
var array = Object.create(FrozenArray);
array = array.concat(['foo']);
array // [Object[0], 'foo']
```

But in some magic way this works just fine when using it from Freezer.

```javascript
var store = new Freezer({
  items: []
});
var array = store.get().items.concat(['foo']);
array // ['foo']
```

There are lots of stackoverflow and blogs on this, but none of them works... except here, and it is really annoying that I can not figure it out :-)

**Comment by arqex** [comment]
Hehe, look at https://github.com/arqex/freezer/blob/master/src/mixins.js#L105

The concat method is also overriten to get the desired behavior.

If you do something like the following with freezer won't work either
```js
[1,2.3].concat( items ); // [1,2,3,(Object[0])]
````

Nevertheless, next version of Freezer will work with real arrays, so concat will work properly again. It comes with some performance penalty for IE9 and IE10, but I think that using real arrays is a mandatory feature if you want Freezer stores to be fully compatible with other frameworks.

**Comment by christianalfoni** [comment]
Ah, now I see the confusion. I have an older version of the source code, where concat is not implemented, but I of course tested this on the newest version using JSFiddle. Typical! :-)

I think this is really interesting stuff. How would you go about overriding the behavior of the real array? Would you add instance methods to the freezer arrays? When playing around with this locally I see that logging the store using instance methods on objects and arrays kinda makes them difficult to read. It is really nice to "hide them" on the prototype.

You know a technique to get best of both worlds?

**Comment by arqex** [comment]
Hehe, sorry, my fault! I've been releasing updates too often :D 

Well, I thought a lot about array inheritance last week and there was a solution that I didn't like much, because it is not standard, but at the end I will use. I will override `__proto__` property of an actual array to point FrozenArray prototype.

`__proto__` will be standarized in ES6, and we will able to use `Object.setPrototype` as well so that ensure it will have more official support in the future. Frameworks like meteor uses this solution and it is the fastest one (just after createa a Array child object).

IE9 and IE10 doesn't support `__proto__` properties, so the methods needs to be overriden one by one, so the library get slower :(

But since its use is not very high, and it will decrease with the time I think it is the way to go.

I found really interesting this article on how we are going to be able to inherit from array in ES6 getting an array: http://www.2ality.com/2013/03/subclassing-builtins-es6.html

**Comment by christianalfoni** [comment]
Aha, I see, thanks for the input, did not know this! I heard that they are aiming for a yearly release of EcmaScript now, hopefully the browser vendors will implement quickly. And with the combination of automatic browser updates we are all looking at a much brighter future :-)
