### ISSUE TITLE
Bower version not updated

### ISSUE THREAD

**Issue by chrismbeckett** [arqex/freezer#91]
Getting a warning when installing with Bower that the version is still 0.4.1.

**Comment by arqex** [comment]
Hey @chrismbeckett 

Thanks to ping me. It's been a while since I used bower the last time. Didn't know that anybody was using it, I was even thinking to remove bower support from the package.

I'll update bower json file when in the next release, you can use the standalone version in the meanwhile.

**Comment by chrismbeckett** [comment]
Agreed - would have thought Bower was yesterday until I started using Google Polymer - all Bower with no plan to switch. Maybe as web components gain popularity Bower will make a comeback :)
